#!/bin/sh
if [ $# -ne 2 ]
then
	echo "Usage: findline n file"
	exit 1
fi
if [ ! -f $2 ]
then
	echo "File does not exist"
	exit 1
fi
(echo "$1"; cat $2) | awk '

	BEGIN { found = 0 }

	NR==1 { linenum = $1 }
	
	NR==(linenum+1) { print $0; found = 1 }

	END { if (found == 0) print "Line not found" }
' 




