#!/bin/sh
if [ $# -ne 2 ]
then
	echo "Usage: findregexp regexp file"
	exit 1
fi
if [ ! -f $2 ]
then
	echo "File does not exist"
	exit 1
fi

cat >/tmp/findregexp.tmp <<EOF

	BEGIN { found = 0 }

	NR==1 { regexp = $0 }
	
	/$1/ { print $0; found = 1 }

	END { if (found == 0) print "Line not found" }

EOF
awk -f /tmp/findregexp.tmp $2



