#!/bin/bash
# https://help.github.com/articles/changing-author-info

old="jim.lawton@gmail.com"
new="jim.lawton@s3group.com"

args=""
reverse=0
if [ ! -z "$1" ]; then
    if [ "$1" = "-a" ]; then
        args="-- --all"
    elif [ "$1" = "-r" ]; then
        reverse=1
    else
        args="$1"
    fi
fi

if [ $reverse -eq 1 ]; then
    tmp=$old
    old=$new
    new=$temp
fi

git filter-branch -f --env-filter '
 
an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"
 
if [ "$GIT_COMMITTER_EMAIL" = "$old" ]
then
    cm="$new"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$old" ]
then
    am="$new"
fi
 
export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
' $args
