#!/bin/bash
# Based on https://help.github.com/articles/changing-author-info

OPTIND=1

all=0
reverse=0
force=0

while getopts "h?arf" opt; do
    case "$opt" in
    h|\?)
        echo "usage: git-fix-author-email [-f|-r|-a] [refspec]"
        exit 0
        ;;
    a)  all=1
        ;;
    r)  reverse=1
        ;;
    f)  force=1
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

old="jim.lawton@gmail.com"
new="jim.lawton@s3group.com"

args=""
reverse=0
if [ $all -eq 1 ]; then
    args="-- --all"
else
    if [ ! -z "$1" ]; then
        args="$1"
    fi
fi

if [ $reverse -eq 1 ]; then
    tmp=$old
    old=$new
    new=$temp
fi

gfbargs=""
if [ $force -eq 1 ]; then
    gfbargs="-f"
fi

git filter-branch $gfbargs --env-filter '
 
an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"
 
if [ "$GIT_COMMITTER_EMAIL" = "$old" ]
then
    cm="$new"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$old" ]
then
    am="$new"
fi
 
export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
' $args
