#!/bin/sh

GUAKE=/usr/local/bin/guake

#${GUAKE} &

${GUAKE} -s 0
sleep 1
${GUAKE} -r "~"
sleep 1

${GUAKE} -n git/cmf-tools
sleep 1
${GUAKE} -r "cmf/tools"
sleep 1
${GUAKE} -e "git status"
sleep 1

${GUAKE} -n git/manifests
sleep 1
${GUAKE} -r "manifests"
sleep 1
${GUAKE} -e "git status"
sleep 1

${GUAKE} -n Work/comcast/repo
sleep 1
${GUAKE} -r "repo"
sleep 1
${GUAKE} -e "git status"
sleep 1

${GUAKE} -n ~
sleep 1
${GUAKE} -r "saturn"
sleep 1
${GUAKE} -e "ssh -AX saturn"
sleep 1

${GUAKE} -n ~
sleep 1
${GUAKE} -r "emulator"
sleep 1
${GUAKE} -e "ssh -AX 192.168.249.81"
sleep 1

exit 0
