#!/bin/bash

usage()
{
    echo "Usage: `basename $0` email-address"
    echo "    'Hurl' the svn url of the current directory to the specified email address"
}

if [ $# != "1" ]; then
    usage
    exit 1
fi

if [ $1 == "-h" ]; then
    usage
    exit 0
fi

url=`svn info | grep URL | awk '{print $2}'`
if [ "$url" == "" ]; then
    exit 1
fi

echo "" | LD_LIBRARY_PATH=/lib:/usr/lib64:/lib64 mail -s $url "$1"
